Deletes corrupt AAE tree after error.
This performs a deletion of a corrupt AAE tree during init phase.
Corruption which may be a result of a power cut etc.
prevents levelDB from opening the index.
Deletion is triggered by a specific error
{badmatch,{error,{db_open,_}}}
during init stage of riak_kv_index_hashtree.

Following warning will be reported:
Error when initialising tree at:
"/var/lib/riak/anti_entropy/v0/1826877...67872".
Error: {badmatch,{error,{db_open,
"Corruption: no meta-nextfile entry in descriptor"}}}

Once deletion is done process crashes (as it used to)
allowing riak_kv_vnode to retry the rebuild (after 1 second).

This should resolve issues with corrupt AAE trees
which could not be fixed without manual deletion
and were causing high CPU load.